// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetosCelo.DB;


#nullable disable

namespace ProjetosCelo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250209181748_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("ProjetosCelo.Models.Amostra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("Amostras");
                });

            modelBuilder.Entity("ProjetosCelo.Models.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("ProjetosCelo.Models.Historico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmostraId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AmostraId");

                    b.ToTable("Historicos");
                });

            modelBuilder.Entity("ProjetosCelo.Models.Responsavel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Responsaveis");
                });

            modelBuilder.Entity("ProjetosCelo.Models.Amostra", b =>
                {
                    b.HasOne("ProjetosCelo.Models.Fornecedor", "Fornecedor")
                        .WithMany("Amostras")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetosCelo.Models.Responsavel", "Responsavel")
                        .WithMany("Amostras")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornecedor");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("ProjetosCelo.Models.Historico", b =>
                {
                    b.HasOne("ProjetosCelo.Models.Amostra", "Amostra")
                        .WithMany("Historicos")
                        .HasForeignKey("AmostraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amostra");
                });

            modelBuilder.Entity("ProjetosCelo.Models.Amostra", b =>
                {
                    b.Navigation("Historicos");
                });

            modelBuilder.Entity("ProjetosCelo.Models.Fornecedor", b =>
                {
                    b.Navigation("Amostras");
                });

            modelBuilder.Entity("ProjetosCelo.Models.Responsavel", b =>
                {
                    b.Navigation("Amostras");
                });
#pragma warning restore 612, 618
        }
    }
}
